"""Ajustes en el modelo usuario

Revision ID: 42e246c4b780
Revises: 4d08d6da3bfd
Create Date: 2025-04-28 16:07:41.211545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42e246c4b780'
down_revision = '4d08d6da3bfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombres', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('apellidos', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('rut', sa.String(length=12), nullable=False))
        batch_op.add_column(sa.Column('password', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('instagram_url', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('facebook_url', sa.String(length=100), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=70),
               existing_nullable=False)
        batch_op.alter_column('telefono',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.create_unique_constraint(None, ['rut'])
        batch_op.drop_column('nombre')
        batch_op.drop_column('contrasena')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contrasena', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('telefono',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=70),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('facebook_url')
        batch_op.drop_column('instagram_url')
        batch_op.drop_column('password')
        batch_op.drop_column('rut')
        batch_op.drop_column('apellidos')
        batch_op.drop_column('nombres')

    # ### end Alembic commands ###
