"""Agrega campo descripcion_respuesta a presupuesto

Revision ID: 4aa14d2bf358
Revises: 1d7c0a5b11e9
Create Date: 2025-04-30 18:47:49.780907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aa14d2bf358'
down_revision = '1d7c0a5b11e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presupuesto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion_solicitud', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('descripcion_respuesta', sa.Text(), nullable=True))
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presupuesto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('descripcion_respuesta')
        batch_op.drop_column('descripcion_solicitud')

    # ### end Alembic commands ###
