"""Primera migración inicial

Revision ID: 4d08d6da3bfd
Revises: 
Create Date: 2025-04-26 20:36:42.312304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d08d6da3bfd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_servicio',
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_categoria'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('rol',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('contrasena', sa.Text(), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email')
    )
    op.create_table('calificacion_cliente',
    sa.Column('id_calificacion', sa.Integer(), nullable=False),
    sa.Column('prestador_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('puntuacion', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['prestador_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_calificacion')
    )
    op.create_table('especialidad_prestador',
    sa.Column('id_especialidad', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria_servicio.id_categoria'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_especialidad')
    )
    op.create_table('presupuesto',
    sa.Column('id_presupuesto', sa.Integer(), nullable=False),
    sa.Column('prestador_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['prestador_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_presupuesto')
    )
    op.create_table('match_trabajo',
    sa.Column('id_match', sa.Integer(), nullable=False),
    sa.Column('presupuesto_id', sa.Integer(), nullable=False),
    sa.Column('fecha_aceptacion', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['presupuesto_id'], ['presupuesto.id_presupuesto'], ),
    sa.PrimaryKeyConstraint('id_match'),
    sa.UniqueConstraint('presupuesto_id')
    )
    op.create_table('resena',
    sa.Column('id_resena', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('prestador_id', sa.Integer(), nullable=False),
    sa.Column('puntuacion', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['match_id'], ['match_trabajo.id_match'], ),
    sa.ForeignKeyConstraint(['prestador_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_resena'),
    sa.UniqueConstraint('match_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resena')
    op.drop_table('match_trabajo')
    op.drop_table('presupuesto')
    op.drop_table('especialidad_prestador')
    op.drop_table('calificacion_cliente')
    op.drop_table('usuario')
    op.drop_table('rol')
    op.drop_table('categoria_servicio')
    # ### end Alembic commands ###
