"""Se agrega campo edad a modelo usuario

Revision ID: 65834ce4cc80
Revises: 4aa14d2bf358
Create Date: 2025-05-06 15:59:30.025378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65834ce4cc80'
down_revision = '4aa14d2bf358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edad', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('edad')

    # ### end Alembic commands ###
