"""Se cambia el campo edad por fecha_nacimiento

Revision ID: 6b611550a9d2
Revises: 65834ce4cc80
Create Date: 2025-05-06 16:21:54.896122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b611550a9d2'
down_revision = '65834ce4cc80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_nacimiento', sa.Date(), nullable=False))
        batch_op.drop_column('edad')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edad', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('fecha_nacimiento')

    # ### end Alembic commands ###
