"""Migracion inicial Limpia

Revision ID: c8b845a490b5
Revises: 
Create Date: 2025-05-13 23:34:08.371434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8b845a490b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_principal',
    sa.Column('id_categoria_principal', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_categoria_principal'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('rol',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('subcategoria',
    sa.Column('id_subcategoria', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('categoria_principal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_principal_id'], ['categoria_principal.id_categoria_principal'], ),
    sa.PrimaryKeyConstraint('id_subcategoria')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=50), nullable=False),
    sa.Column('apellidos', sa.String(length=50), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('rut', sa.String(length=12), nullable=False),
    sa.Column('email', sa.String(length=70), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('instagram_url', sa.String(length=100), nullable=True),
    sa.Column('facebook_url', sa.String(length=100), nullable=True),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('servicio',
    sa.Column('id_servicio', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('subcategoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subcategoria_id'], ['subcategoria.id_subcategoria'], ),
    sa.PrimaryKeyConstraint('id_servicio')
    )
    op.create_table('presupuesto',
    sa.Column('id_presupuesto', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('prestador_id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('descripcion_solicitud', sa.Text(), nullable=False),
    sa.Column('descripcion_respuesta', sa.Text(), nullable=True),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['prestador_id'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id_servicio'], ),
    sa.PrimaryKeyConstraint('id_presupuesto')
    )
    op.create_table('usuario_servicio',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id_servicio'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'servicio_id')
    )
    op.create_table('match_trabajo',
    sa.Column('id_match', sa.Integer(), nullable=False),
    sa.Column('presupuesto_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['presupuesto_id'], ['presupuesto.id_presupuesto'], ),
    sa.PrimaryKeyConstraint('id_match'),
    sa.UniqueConstraint('presupuesto_id')
    )
    op.create_table('calificacion',
    sa.Column('id_calificacion', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('receptor_id', sa.Integer(), nullable=False),
    sa.Column('puntuacion', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.CheckConstraint('puntuacion >= 1 AND puntuacion <= 5', name='Verifica_puntuación'),
    sa.ForeignKeyConstraint(['autor_id'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['match_id'], ['match_trabajo.id_match'], ),
    sa.ForeignKeyConstraint(['receptor_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_calificacion'),
    sa.UniqueConstraint('match_id', 'autor_id', name='calificacion_unica')
    )
    op.create_table('resena',
    sa.Column('id_resena', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('prestador_id', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['match_id'], ['match_trabajo.id_match'], ),
    sa.ForeignKeyConstraint(['prestador_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_resena'),
    sa.UniqueConstraint('match_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resena')
    op.drop_table('calificacion')
    op.drop_table('match_trabajo')
    op.drop_table('usuario_servicio')
    op.drop_table('presupuesto')
    op.drop_table('servicio')
    op.drop_table('usuario')
    op.drop_table('subcategoria')
    op.drop_table('rol')
    op.drop_table('categoria_principal')
    # ### end Alembic commands ###
